### ISSUE TITLE
Timestamps in Images

### ISSUE THREAD

**Issue by jsigman** [JWally/procare-media-downloader#1]
First, love the webapp. It is going to allow my wife and I to bulk store the photos we get from our daycare in Cary. So thank you for putting this out there!

I wonder if there is a way to timestamp the images that are downloaded? The filenames encode the time of the photo, but this metadata is stripped from the jpeg object. For example, the file `img_1665512507858249_photo.jpg`

In python:

```python
import datetime
datetime.datetime.fromtimestamp(1665512507.858249)
```

Results in:

```console
datetime.datetime(2022, 10, 11, 14, 21, 47, 858249)
```

Which is when the photo was taken. Is there a fundamental reason this timestamp couldn't be added back into the image metadata seamlessly? If so, I'd love to learn how to do this, and can plan to add this in myself.

If not, I'll probably post a little post-hoc script for doing this after they're downloaded, and will share it back here.

Thanks!
Johnny

**Comment by jsigman** [comment]
https://github.com/jsigman/procare_photo_timestamper

**Comment by JWally** [comment]
Sorry for the (extremely) late response.

I hadn't been in Procare or this Repo for like the last 2 years and didn't realize it was broken because of updates.

I fixed it so it now works and downloads around 30x faster.

The files are also named `${date}-${id}.${extension}` so you have the date the picture was taken.

Future enhancements: update the EXIF data in the script itself - if possible.

**Comment by JWally** [comment]
files are now named as date-id.extension.
